id: A8F8270F0
base_file: fA134.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:34:54.335460
  last_modified_at: 2022-06-11 13:34:54.335467
